TYPE 2
DISPLAY Check Square Collision
ICON Object.png
CONDITION 0
ARG object,4
ARG iterator variable,3
ARG return variable,3
ARG reset result,2
if(!4!)
	!3! = 128;
for(!2! = 0; !2! < 128; !2!++)
{
	if(Instances[!2!].InUse && !2! != AppliesTo && Instances[!2!].EName == !1!)
	{
		if(Instances[AppliesTo].X <= Instances[!2!].X + Instances[!2!].Width
			&& Instances[AppliesTo].X + Instances[AppliesTo].Width >= Instances[!2!].X
			&& Instances[AppliesTo].Y <= Instances[!2!].Y + Instances[!2!].Height
			&& Instances[AppliesTo].Y + Instances[AppliesTo].Height >= Instances[!2!].Y)
		{
			!3! = !2!;
			break;
		}

	}
}